:toc:
:toclevels: 2
:icons: font


= Howto: Release

toc::[]

== Scope of the document

This document helps developers and maintainers to draft releases.

== Update the codebase

Every number is a commit.

** 1. Replace all `@since TODO` and `@deprecated(since = "TODO")` in the code with the version you look forward to release.
** 2. Remove `-SNAPSHOT` in `build.gradle.kts` or adjust the version format, depending on the project. You may need to adjust the version too, in case you don't want to release a patch version but a minor one.
** 3. If all checks are green, increase the version, for example, if we release 1.0.0, increase it to 1.0.1-SNAPSHOT.

== Publish the changelog

If you click on the "Releases" tab on GitHub, you see a draft. Edit the draft and make sure the tag fits the version you want to release. +
You can copy the release tab changelogs and use them on Discord or other platforms, where we announce our changes.

== Publish the end user artifact

=== Special treatment
==== FastAsyncWorldEdit

On Jenkins link:https://ci.athion.net/job/FastAsyncWorldEdit/[Jenkins] we're using the release plugin to highlight releases. Specify the version you want to release and hit the button link:https://ci.athion.net/job/FastAsyncWorldEdit/release/[here].

==== PlotSquared
For PlotSquared, add a `-Premium` suffix to the build step, if you're building the artifact. md_5 recommended us to do that.

Upload the release artifact (not the artifact with the already increased build number!) to either Spigot or dev.bukkit.org, if the plugin is not distributed from external sources, and paste the previously assembled changelog in the changelog field.

If you are unable to publish a release on a distribution platform, let a project maintainer know beforehand.

[NOTE]
dev.bukkit.org moderates submitted files by "first in first out" rule. The moderation times are Sunday, Monday, Tuesday, Wednesday, Thursday: 9:00 AM - 5:00 PM GMT.

'''

If you need help, don't hesitate to ask maintainers who did releases in the past.
